// Code generated by MockGen. DO NOT EDIT.
// Source: ./ocppj/client.go
//
// Generated by this command:
//
//	mockgen -source=./ocppj/client.go -package=mocks -destination=./ocppj/internal/mocks/client_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	net "net"
	reflect "reflect"

	websocket "github.com/road-labs/ocppj-go/websocket"
	gomock "go.uber.org/mock/gomock"
)

// MockWebsocketClient is a mock of WebsocketClient interface.
type MockWebsocketClient struct {
	ctrl     *gomock.Controller
	recorder *MockWebsocketClientMockRecorder
	isgomock struct{}
}

// MockWebsocketClientMockRecorder is the mock recorder for MockWebsocketClient.
type MockWebsocketClientMockRecorder struct {
	mock *MockWebsocketClient
}

// NewMockWebsocketClient creates a new mock instance.
func NewMockWebsocketClient(ctrl *gomock.Controller) *MockWebsocketClient {
	mock := &MockWebsocketClient{ctrl: ctrl}
	mock.recorder = &MockWebsocketClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebsocketClient) EXPECT() *MockWebsocketClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWebsocketClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWebsocketClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWebsocketClient)(nil).Close))
}

// GracefulClose mocks base method.
func (m *MockWebsocketClient) GracefulClose(ctx context.Context, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GracefulClose", ctx, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// GracefulClose indicates an expected call of GracefulClose.
func (mr *MockWebsocketClientMockRecorder) GracefulClose(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulClose", reflect.TypeOf((*MockWebsocketClient)(nil).GracefulClose), ctx, text)
}

// ID mocks base method.
func (m *MockWebsocketClient) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockWebsocketClientMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockWebsocketClient)(nil).ID))
}

// LocalAddr mocks base method.
func (m *MockWebsocketClient) LocalAddr() net.Addr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocalAddr")
	ret0, _ := ret[0].(net.Addr)
	return ret0
}

// LocalAddr indicates an expected call of LocalAddr.
func (mr *MockWebsocketClientMockRecorder) LocalAddr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocalAddr", reflect.TypeOf((*MockWebsocketClient)(nil).LocalAddr))
}

// Read mocks base method.
func (m *MockWebsocketClient) Read() (websocket.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read")
	ret0, _ := ret[0].(websocket.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockWebsocketClientMockRecorder) Read() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockWebsocketClient)(nil).Read))
}

// RemoteHost mocks base method.
func (m *MockWebsocketClient) RemoteHost() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoteHost")
	ret0, _ := ret[0].(string)
	return ret0
}

// RemoteHost indicates an expected call of RemoteHost.
func (mr *MockWebsocketClientMockRecorder) RemoteHost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoteHost", reflect.TypeOf((*MockWebsocketClient)(nil).RemoteHost))
}

// Subprotocol mocks base method.
func (m *MockWebsocketClient) Subprotocol() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subprotocol")
	ret0, _ := ret[0].(string)
	return ret0
}

// Subprotocol indicates an expected call of Subprotocol.
func (mr *MockWebsocketClientMockRecorder) Subprotocol() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subprotocol", reflect.TypeOf((*MockWebsocketClient)(nil).Subprotocol))
}

// Write mocks base method.
func (m *MockWebsocketClient) Write(arg0 websocket.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockWebsocketClientMockRecorder) Write(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockWebsocketClient)(nil).Write), arg0)
}
