// Code generated by MockGen. DO NOT EDIT.
// Source: ./ocppj/client_hooks.go
//
// Generated by this command:
//
//	mockgen -source=./ocppj/client_hooks.go -package=mocks -destination=./ocppj/mocks/client_hooks_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ocppj "github.com/e-flux-platform/ocppj-go/ocppj"
	message "github.com/e-flux-platform/ocppj-go/ocppj/message"
	gomock "go.uber.org/mock/gomock"
)

// MockClientHooks is a mock of ClientHooks interface.
type MockClientHooks struct {
	ctrl     *gomock.Controller
	recorder *MockClientHooksMockRecorder
	isgomock struct{}
}

// MockClientHooksMockRecorder is the mock recorder for MockClientHooks.
type MockClientHooksMockRecorder struct {
	mock *MockClientHooks
}

// NewMockClientHooks creates a new mock instance.
func NewMockClientHooks(ctrl *gomock.Controller) *MockClientHooks {
	mock := &MockClientHooks{ctrl: ctrl}
	mock.recorder = &MockClientHooksMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientHooks) EXPECT() *MockClientHooksMockRecorder {
	return m.recorder
}

// OnCallErrorRead mocks base method.
func (m *MockClientHooks) OnCallErrorRead(arg0 context.Context, arg1 *ocppj.Client, arg2 message.CallError) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnCallErrorRead", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnCallErrorRead indicates an expected call of OnCallErrorRead.
func (mr *MockClientHooksMockRecorder) OnCallErrorRead(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCallErrorRead", reflect.TypeOf((*MockClientHooks)(nil).OnCallErrorRead), arg0, arg1, arg2)
}

// OnCallErrorWritten mocks base method.
func (m *MockClientHooks) OnCallErrorWritten(arg0 context.Context, arg1 *ocppj.Client, arg2 message.CallError) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnCallErrorWritten", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnCallErrorWritten indicates an expected call of OnCallErrorWritten.
func (mr *MockClientHooksMockRecorder) OnCallErrorWritten(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCallErrorWritten", reflect.TypeOf((*MockClientHooks)(nil).OnCallErrorWritten), arg0, arg1, arg2)
}

// OnCallRead mocks base method.
func (m *MockClientHooks) OnCallRead(arg0 context.Context, arg1 *ocppj.Client, arg2 message.Call) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnCallRead", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnCallRead indicates an expected call of OnCallRead.
func (mr *MockClientHooksMockRecorder) OnCallRead(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCallRead", reflect.TypeOf((*MockClientHooks)(nil).OnCallRead), arg0, arg1, arg2)
}

// OnCallResultRead mocks base method.
func (m *MockClientHooks) OnCallResultRead(arg0 context.Context, arg1 *ocppj.Client, arg2 message.CallResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnCallResultRead", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnCallResultRead indicates an expected call of OnCallResultRead.
func (mr *MockClientHooksMockRecorder) OnCallResultRead(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCallResultRead", reflect.TypeOf((*MockClientHooks)(nil).OnCallResultRead), arg0, arg1, arg2)
}

// OnCallResultWritten mocks base method.
func (m *MockClientHooks) OnCallResultWritten(arg0 context.Context, arg1 *ocppj.Client, arg2 message.CallResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnCallResultWritten", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnCallResultWritten indicates an expected call of OnCallResultWritten.
func (mr *MockClientHooksMockRecorder) OnCallResultWritten(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCallResultWritten", reflect.TypeOf((*MockClientHooks)(nil).OnCallResultWritten), arg0, arg1, arg2)
}

// OnCallWritten mocks base method.
func (m *MockClientHooks) OnCallWritten(arg0 context.Context, arg1 *ocppj.Client, arg2 message.Call) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnCallWritten", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnCallWritten indicates an expected call of OnCallWritten.
func (mr *MockClientHooksMockRecorder) OnCallWritten(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCallWritten", reflect.TypeOf((*MockClientHooks)(nil).OnCallWritten), arg0, arg1, arg2)
}

// OnInvalidMessageRead mocks base method.
func (m *MockClientHooks) OnInvalidMessageRead(arg0 context.Context, arg1 *ocppj.Client, arg2 []byte, arg3 error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnInvalidMessageRead", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnInvalidMessageRead indicates an expected call of OnInvalidMessageRead.
func (mr *MockClientHooksMockRecorder) OnInvalidMessageRead(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnInvalidMessageRead", reflect.TypeOf((*MockClientHooks)(nil).OnInvalidMessageRead), arg0, arg1, arg2, arg3)
}
