// Code generated by MockGen. DO NOT EDIT.
// Source: ./ocppj/rate.go
//
// Generated by this command:
//
//	mockgen -source=./ocppj/rate.go -package=mocks -destination=./ocppj/mocks/rate_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ocppj "github.com/e-flux-platform/ocppj-go/ocppj"
	message "github.com/e-flux-platform/ocppj-go/ocppj/message"
	gomock "go.uber.org/mock/gomock"
)

// MockClientRateLimiter is a mock of ClientRateLimiter interface.
type MockClientRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockClientRateLimiterMockRecorder
	isgomock struct{}
}

// MockClientRateLimiterMockRecorder is the mock recorder for MockClientRateLimiter.
type MockClientRateLimiterMockRecorder struct {
	mock *MockClientRateLimiter
}

// NewMockClientRateLimiter creates a new mock instance.
func NewMockClientRateLimiter(ctrl *gomock.Controller) *MockClientRateLimiter {
	mock := &MockClientRateLimiter{ctrl: ctrl}
	mock.recorder = &MockClientRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientRateLimiter) EXPECT() *MockClientRateLimiterMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockClientRateLimiter) Allow(ctx context.Context, client *ocppj.Client, msg message.Message) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", ctx, client, msg)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Allow indicates an expected call of Allow.
func (mr *MockClientRateLimiterMockRecorder) Allow(ctx, client, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockClientRateLimiter)(nil).Allow), ctx, client, msg)
}
