// Code generated by MockGen. DO NOT EDIT.
// Source: ./ocppj/server_hooks.go
//
// Generated by this command:
//
//	mockgen -source=./ocppj/server_hooks.go -package=mocks -destination=./ocppj/mocks/server_hooks_mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	ocppj "github.com/e-flux-platform/ocppj-go/ocppj"
	gomock "go.uber.org/mock/gomock"
)

// MockServerHooks is a mock of ServerHooks interface.
type MockServerHooks struct {
	ctrl     *gomock.Controller
	recorder *MockServerHooksMockRecorder
	isgomock struct{}
}

// MockServerHooksMockRecorder is the mock recorder for MockServerHooks.
type MockServerHooksMockRecorder struct {
	mock *MockServerHooks
}

// NewMockServerHooks creates a new mock instance.
func NewMockServerHooks(ctrl *gomock.Controller) *MockServerHooks {
	mock := &MockServerHooks{ctrl: ctrl}
	mock.recorder = &MockServerHooksMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerHooks) EXPECT() *MockServerHooksMockRecorder {
	return m.recorder
}

// OnClientConnected mocks base method.
func (m *MockServerHooks) OnClientConnected(arg0 context.Context, arg1 *ocppj.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnClientConnected", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnClientConnected indicates an expected call of OnClientConnected.
func (mr *MockServerHooksMockRecorder) OnClientConnected(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnClientConnected", reflect.TypeOf((*MockServerHooks)(nil).OnClientConnected), arg0, arg1)
}

// OnClientDisconnected mocks base method.
func (m *MockServerHooks) OnClientDisconnected(arg0 context.Context, arg1 *ocppj.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnClientDisconnected", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnClientDisconnected indicates an expected call of OnClientDisconnected.
func (mr *MockServerHooksMockRecorder) OnClientDisconnected(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnClientDisconnected", reflect.TypeOf((*MockServerHooks)(nil).OnClientDisconnected), arg0, arg1)
}

// OnUpgradeRequested mocks base method.
func (m *MockServerHooks) OnUpgradeRequested(ctx context.Context, req *http.Request, selectedProtocol string) (*ocppj.UpgradeRequestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnUpgradeRequested", ctx, req, selectedProtocol)
	ret0, _ := ret[0].(*ocppj.UpgradeRequestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OnUpgradeRequested indicates an expected call of OnUpgradeRequested.
func (mr *MockServerHooksMockRecorder) OnUpgradeRequested(ctx, req, selectedProtocol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnUpgradeRequested", reflect.TypeOf((*MockServerHooks)(nil).OnUpgradeRequested), ctx, req, selectedProtocol)
}
